// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyBzBFAHaewk_tM7JOgDmsXQR1jBZetjw',
    appId: '1:589974357149:web:13ac6e0f797dc9ce8b0074',
    messagingSenderId: '589974357149',
    projectId: 'wydatki-50fef',
    authDomain: 'wydatki-50fef.firebaseapp.com',
    storageBucket: 'wydatki-50fef.appspot.com',
    measurementId: 'G-7DCJB3NK3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMfqHlNWfiXINHUGrX8wqw0D659-e7fs',
    appId: '1:589974357149:android:e4bdcdcae178e92a8b0074',
    messagingSenderId: '589974357149',
    projectId: 'wydatki-50fef',
    storageBucket: 'wydatki-50fef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0kXrMeuadANb3WlqpboJQsSRTAoEoO0',
    appId: '1:589974357149:ios:eeb4900ab872f1608b0074',
    messagingSenderId: '589974357149',
    projectId: 'wydatki-50fef',
    storageBucket: 'wydatki-50fef.appspot.com',
    iosClientId: '589974357149-nh2u5737qo3f3r4ffqlfavvsuak7acor.apps.googleusercontent.com',
    iosBundleId: 'com.katarzynadominik.wydatki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0kXrMeuadANb3WlqpboJQsSRTAoEoO0',
    appId: '1:589974357149:ios:eeb4900ab872f1608b0074',
    messagingSenderId: '589974357149',
    projectId: 'wydatki-50fef',
    storageBucket: 'wydatki-50fef.appspot.com',
    iosClientId: '589974357149-nh2u5737qo3f3r4ffqlfavvsuak7acor.apps.googleusercontent.com',
    iosBundleId: 'com.katarzynadominik.wydatki',
  );
}
